# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[(b'fibonacci', b'fibonacci'), (b'power', b'power'), (b'github', b'github')], max_length=20),
        ),
    ]
