# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_auto_20170103_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
