# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-17 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_auto_20170117_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_info',
            field=models.CharField(default=b'contact', max_length=20, verbose_name=b'ContactInfo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[(b'power', b'power'), (b'github', b'github')], max_length=20),
        ),
    ]
