# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-17 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_auto_20170117_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact_info',
        ),
        migrations.AlterField(
            model_name='job',
            name='argument',
            field=models.CharField(help_text=b'helloooooo', max_length=100),
        ),
    ]
