# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_auto_20170117_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.AlterField(
            model_name='job',
            name='argument',
            field=models.CharField(help_text=b'Enter the github profile name', max_length=100),
        ),
    ]
